### ISSUE TITLE
client.get_sigma_rule different result to client.get_sigma_rule_by_text

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1740]
Running the following command:

```
rule = client.get_sigma_rule(rule_uuid='5266a592-b793-11ea-b3de-0242ac130004')
rule.es_query
``` 

Gives:
```
'*apt\\-get\\ install\\ zmap*'
```

Vs:
```
rule_text = """title: Suspicious Installation of Zenmap
id: 5266a592-b793-11ea-b3de-0242ac130004
description: Detects suspicious installation of Zenmap
references:
    - https://rmusser.net/docs/ATT&CK-Stuff/ATT&CK/Discovery.html
author: Alexander Jaeger
date: 2020/06/26
modified: 2020/06/26
tags:
    - attack.discovery
    - attack.t1046
logsource:
    product: linux
    service: shell
detection:
    keywords:
        # Generic suspicious commands
        - '*apt-get install zmap*'
    condition: keywords
falsepositives:
    - Unknown
level: high"""
rule2 = client.get_sigma_rule_by_text(rule_text)
rule2.es_query
```

Gives:

```'(data_type:("shell\\:zsh\\:history" OR "bash\\:history\\:command" OR "apt\\:history\\:line" OR "selinux\\:line") AND "*apt\\-get\\ install\\ zmap*")'
```
