### ISSUE TITLE
tagger analyzer not functiong properly 

### ISSUE THREAD

**Issue by rushattac** [google/timesketch#1820]
**Describe the bug**
After upgrade TimeSketch to version: 20210602 the tagger analyzer is not functioning with custom tags

**To Reproduce**
1. Import plaso file with evtx data 
2. Add the following tagging rule to tags.yaml
```yaml
logon_tagger:  
  query_string: 'data_type: "windows:evtx:record" AND source_name: "Microsoft-Windows-Security-Auditing" AND event_identifier: 4688'
  tags: ['logon']
  save_search: true
  search_name: 'logon'
```
3. run tagger analyzer

**Expected behavior**
The tagger analyzer to run correctly as in previous versions.

**Desktop (please complete the following information):**
-OS:Ubuntu 20.04.2 LTS
-Browser : Firefox
-Version: 86.0

**Additional context**
The following exception is thrown once the tagger analyzer is ran:
```
Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/analyzers/interface.py", line 995, in run_wrapper result = self.run() File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/analyzers/tagger.py", line 48, in run tag_result = self.tagger(name, tag_config) File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/analyzers/tagger.py", line 100, in tagger if expression: UnboundLocalError: local variable 'expression' referenced before assignment
```
