### ISSUE TITLE
IOCTypes - PR 2045

### ISSUE THREAD

**Issue by lprat** [google/timesketch#2050]
**Is your feature request related to a problem? Please describe.**
Hi @tomchop ,
Can you add possibility to configure from file /etc/timesketch/ioctype.yaml (by example), the choice of IOC Type that you can use in your interface intelligence ? Because today, these values are fixed: https://github.com/google/timesketch/blob/8f74f175a6ad1ce3d8903c895b9810ce5b6abe01/timesketch/frontend/src/components/Common/TsIOCMenu.vue#L67-L76

  
Exemple of file ioctype.yaml (user can add new IOC type like URL, email, ...):
```
fs_path:
        regex: /^(\/[\S]+)+$/i
hostname:
        regex: /^([-\w]+\.)+[a-z]{2,}$/i
ipv4:
        regex: /^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/g
hash_sha256:
        regex: /^[0-9a-f]{64}$/i
hash_sha1:
        regex: /^[0-9a-f]{40}$/i
hash_md5:
        regex: /^[0-9a-f]{32}$/i
other:
        regex: /./g
```

**Describe the solution you'd like**
Change fixed value https://github.com/google/timesketch/blob/8f74f175a6ad1ce3d8903c895b9810ce5b6abe01/timesketch/frontend/src/components/Common/TsIOCMenu.vue#L67-L76 by load value type from config file.

Thank for your help!
Lionel
