### ISSUE TITLE
BigQuery Analyzer Plugin

### ISSUE THREAD

**Issue by anttitikkanen** [google/timesketch#2130]
**Is your feature request related to a problem? Please describe.**
I have threat indicators stored in a BigQuery table. I'd like to match these indicators (file hashes, IP's, domains) to Timesketch events to identify known badness.

**Describe the solution you'd like**
An analyzer plugin that matches selected fields from Timesketch events against data in a BigQuery table. The user can configure this using a new configuration file with entries like:

```
matcher_rule_name:
     event_field_name: sha256_hash # Timesketch events with this field will be matched
     bq_project: 'project_name' # Use this Google Cloud project to run the BQ job
     bq_query: 'SELECT DISTINCT hash FROM project.dataset.tablename WHERE hash IN UNNEST(@sha256_hash)' # The query to use for matching
     tags: ['bigquery-sha256-match'] # Tags to apply if matching data is found in the BQ table
     emojis: ['SKULL'] # Emojis to apply if matching data is found in the BQ table
```

I'll be happy to contribute this feature myself!
