### ISSUE TITLE
Sigma parsing error with stars

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#2550]
There seem to be a problem in https://github.com/google/timesketch/blob/master/timesketch/lib/sigma_util.py#L124 when having a mixture of terms surrounded by "" and ** that the first word is always getting "" around them.

- [x] test cases
- [x] fix the issue

**Comment by jaegeral** [comment]
The question is if the following: 

```
"foobar" OR *barfoo*
```

if the `"` is the same as `*`

Sample rule:

```
title: test terms
id: 6d8ca9f2-79e2-44bd-957d-b4d810374972
description: Rule to test combination of three words and how they are parsed
author: Alexander Jaegerdate: 2023/02/13
modified: 2023/02/13
falsepositives:
    - Legitimate usage of the terms
tags:
    - testrule
status: experimental
level: medium
detection:
    keywords:
        - '*foobar*'
        - '*bla*'
        - '*barfoo*'
    condition: keywords
```

**Comment by jaegeral** [comment]
I could not re-verify why that was introduced in the first place, so I am going to remove it for now

**Comment by jaegeral** [comment]
Using this rule:

```
title: test terms
id: 6d8ca9f2-79e2-44bd-957d-b4d810374972
description: Rule to test combination of three words and how they are parsed
author: Alexander Jaeger
date: 2023/02/13
modified: 2023/02/13
falsepositives:
    - Legitimate usage of the terms
tags:
    - testrule
status: experimental
level: medium
detection:
    keywords:
        - '*onlyoneterm*'
        - '*two words*'
        - '*completely new mot*'
    condition: keyword
```


is currently parsed to:
```
("onlyoneterm" OR "two words" OR "completely new mot")
```

Which should be fine.
