### ISSUE TITLE
DFIQ UI Bug

### ISSUE THREAD

**Issue by RoemIko** [google/timesketch#3070]
**Describe the bug**
DFIQ templates do not display anything if saved searches are added

**To Reproduce**
1. Have the following DFIQ template
```
display_name: Sharepoint exfiltration from auditlogs
description:
  summary:
  details:
  references:
    -
type: approach
id: Q0001.01
tags:
 - microsoft365
view:
  analysis:
  - name: OpenSearch
    steps:
    - description: &filter-desc Filter Sharepoint events that may indicate exfiltration attempts.
      type: opensearch-query
      value: 'data_type:"auditlogs" AND (workload:"SharePoint" AND recordtype:("SharePoint" OR 4 OR 6 OR 14 OR 33)) AND operation:("FileDownloaded" OR "AnonymousLinkCreated" OR "SecureLinkCreated" OR "FileSyncDownloadedFull" OR "FileSyncDownloadedPartial")'
```

I keep getting No question found with this ID when i remove the analysis: yaml entry it gets fixed and the question can be added. I have no error logs in wsgi.log or in worker.log

**Expected behavior**
I expect the UI to show me questions and saved searches related to a question i am trying to answer

**Desktop (please complete the following information):**
 - OS: 5.15.146.1-microsoft-standard-WSL2
 - Browser Tried Chrome and Edge
 - Version 123.0.6312.122 123.0.2420.81
